# Generated by Django 4.1.7 on 2023-02-26 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
